#!/usr/bin/env ruby

# git config --local core.hooksPath .githooks/

yellow = "\033[1;33m"
nocolor = "\033[0m"

puts "#{yellow}[StandardRB]#{nocolor} Running"
files = `
  git diff --cached --name-only --diff-filter=AMR |
  egrep '\.rb$|\.rake$'
`
files = files.split("\n")
if files.any?
  successful = system("bundle exec standardrb #{files.join(" ")} --format progress --force-exclusion")
  exit 1 unless successful
end
