name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    env:
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
      HTTP_BASIC_AUTH_NAME: authname
      HTTP_BASIC_AUTH_PASSWORD: authpassword
      GEOIP_GEOLITE2_PATH: .
      GEOIP_GEOLITE2_COUNTRY_FILENAME: GeoLite2-Country.mmdb
      MAXMIND_LICENSE_KEY: ejLzWgHyDqnOOoTy

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev
    - name: MaxMind Database
      run: |
        wget --quiet --output-document "./maxmind.mmdb" "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${{ env.MAXMIND_LICENSE_KEY }}&suffix=tar.gz"
        tar -xvf ./maxmind.mmdb --directory ./ --no-anchored --strip-components=1 ${{ env.GEOIP_GEOLITE2_COUNTRY_FILENAME }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build App
      run: |
        bundle config path vendor/bundle
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup
        bin/rails assets:precompile
    - name: Linter
      run: bundle exec standardrb
    - name: Tests
      run: bundle exec rspec
